### ISSUE TITLE
case dotts 

### ISSUE THREAD

**Issue by joldibaev** [oceanroleplay/pawn-community-tool#1]
When i press 'format document' (VSCode) from this
![image](https://user-images.githubusercontent.com/44665144/71681165-c66f5a80-2dad-11ea-91fe-b341ad2672a0.png)
becomes this:
![image](https://user-images.githubusercontent.com/44665144/71681267-08000580-2dae-11ea-93de-5c3afb18dba6.png)

**Comment by vijayymmeena** [comment]
sorry for the delay, I was busy with something. I am checking this now, and give you updates
