### ISSUE TITLE
Question about tasks.json

### ISSUE THREAD

**Issue by hoooft** [oceanroleplay/pawn-community-tool#2]
Hello so I am trying to run the compiler in vs code and I dont have too much experience with .json files so this is my problem:

I put the compiler path and try to compile a standard gamemode (grandlarc.pwn).
![image](https://user-images.githubusercontent.com/58036491/107362875-a2feff00-6ad9-11eb-9e31-c920a9e7497d.png)

But when i try to compile it I become this errors:
![image](https://user-images.githubusercontent.com/58036491/107362915-b27e4800-6ad9-11eb-8a6b-1c0f191c7c60.png)

But when i delete this 3 lines of the "args" in "tasks":
![image](https://user-images.githubusercontent.com/58036491/107362981-c7f37200-6ad9-11eb-98fc-e93549e09e8a.png)

The file will compile but it wont be save in the "gamemode" folder instead it will be saved in the {workspaceRoot}. Is this an error or I am doing something wrong in the .json file?

Thank you for your time! Also great job doing the documentation in the Indian Ocean Roleplay wiki!

**Comment by vijayymmeena** [comment]
Hello

sorry, I can't read your error logs because it's not in English.

can you provide your tasks.json from .vscode folder, so that I can reproduce the issue.

**Comment by vijayymmeena** [comment]
It is maybe args, can you try without -d3. it will compile normally.

**Comment by hoooft** [comment]
Oh sorry, my bad, i didnt realize it was in german. Here are the logs in English:

`In line: 1 character: 101
+ ... in32 / pawno / pawncc.exe gamemodes \ grandlarc.pwn -Dgamemodes -; + - (+ -d3
+ ~
Expression is missing after the unary operator "+".
In line: 1 character: 102
+ ... in32 / pawno / pawncc.exe gamemodes \ grandlarc.pwn -Dgamemodes -; + - (+ -d3
+ ~~
Unexpected token "-d" in expression or statement.
In line: 1 character: 104
+ ... in32 / pawno / pawncc.exe gamemodes \ grandlarc.pwn -Dgamemodes -; + - (+ -d3
+ ~
Unexpected token "3" in expression or instruction.
In line: 1 character: 104
+ ... in32 / pawno / pawncc.exe gamemodes \ grandlarc.pwn -Dgamemodes -; + - (+ -d3
+ ~
Closing ")" is missing from an expression.
    + CategoryInfo: ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId: MissingExpressionAfterOperator`

Here is the .json file as .txt also I made the .json file following the instructions in git.
[tasks.txt](https://github.com/oceanroleplay/pawn-community-tool/files/5951543/tasks.txt)

I try without -d3 and this error shows up:
`Expression is missing after the unary operator "+".
     + CategoryInfo: ParserError: (:) [], ParentContainsErrorRecordException
     + FullyQualifiedErrorId: MissingExpressionAfterOperator

The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command D:\samp\server\samp037_svr_R2-1-1_win32/pawno/pawncc.exe gamemodes\grandlarc.pwn -Dgamemodes -;+ -(+" failed to launch (exit code: 1).
`

**Comment by vijayymmeena** [comment]
okay, I am testing right now. just wait here.

**Comment by vijayymmeena** [comment]
I would like to know your pawn version too.

**Comment by vijayymmeena** [comment]
there is nothing wrong with your task.json, it is maybe your pawncc version. you could try manual compile to confirm it. 

also open gamemode folder inside vscode, it will then place the compiled file into gamemode.

`pawncc.exe grandlarc.pwn -Dgamemodes -;+ -(+ -d3`

**Comment by hoooft** [comment]
I am not sure I think it`s 1.0. Because that is the version that comes when I downloaded the windows server from the official SA-MP page.

https://www.sa-mp.com/download.php

**Comment by vijayymmeena** [comment]
```
{
	"version": "2.0.0",
	"tasks": [
		{
			"label": "build-normal",
			"type": "shell",
			"command": "${workspaceRoot}\\pawno\\pawncc.exe",
			"runOptions": {
				"instanceLimit": 1,
			},
			"args": [
				"../${relativeFile}",
				"-Dgamemodes",
				"-;+",
				"-(+",
				"-d3"
			],
			"group": {
				"kind": "build",
				"isDefault": true
			},
			"isBackground": false,
			"presentation": {
				"reveal": "always",
				"panel": "dedicated"
			},
			"problemMatcher": {
				"owner": "pawn",
				"fileLocation": [
					"relative",
					"${workspaceRoot}"
				],
				"pattern": {
					"regexp": "^(.*?)\\(([0-9]*)[- 0-9]*\\) \\: (fatal error|error|warning) [0-9]*\\: (.*)$",
					"file": 1,
					"location": 2,
					"severity": 3,
					"message": 4
				}
			}
		}
	],
}
```

open the samp-server folder in vscode and execute build task. it will compile.

I just tested it with Pawn compiler 3.2.3664

# Do you have discord?

**Comment by hoooft** [comment]
Will try it later, need to get back to work.

**Comment by vijayymmeena** [comment]
## Join https://discord.gg/Xq9k3hr

I will assist you there, we will also discuss for improvements.

### Thank you

**Comment by hoooft** [comment]
Thank you!
