### ISSUE TITLE
Go to definition

### ISSUE THREAD

**Issue by Jedrzej94** [oceanroleplay/pawn-community-tool#3]
You sure that Go to definition works? (F12) - whenever I hit that button it redirects me to some random garbage in my code (some MySQL examples in dependencies).

Does "Go to definition" supports modular programming? Maybe that's an issue here?

**Comment by vijayymmeena** [comment]
It works good. you just have to understand, how does the pawn community tool collect definitions. The extension scan your entire workspace and collect functions and it's parameter and store them in array. 

so in your case, there might be multiple entries in your workspace, so it might goto the first one. However, if you provide examples for testing's. I can test and improve the plugin. otherwise, goto def works good.

You can also join our discord channel for quick  discussions. https://discord.gg/Xq9k3hr

**Comment by Jedrzej94** [comment]
Whenever I hit F12 it jumps straight into some SA-MP-MySQL dependecy (which I dunno where it came from, probably one of the examples from the libraries I've imported).

It would be difficult to give you a code to test it on, since I run on very deep modular:
![image](https://user-images.githubusercontent.com/15942408/110012257-a5432a80-7d20-11eb-95e9-981fc481f65f.png)

Believe me, function(s) I'm trying to navigate to always redirect me to:
![image](https://user-images.githubusercontent.com/15942408/110012382-c3a92600-7d20-11eb-8275-ea9060d55f4f.png)

**Comment by vijayymmeena** [comment]
I am unfamiliar with your workspace design as it has dependencies. as I can see your workspace have lot's of pwn files, that's why it's collecting the wrong definition, try to load gamemode folder as workspace. So that, extension find functions inside gamemode folder only.

however, I guess your issue has few points, like if we can configure the plugin for folders to look reference would be better.

**Comment by vijayymmeena** [comment]
and if you want to load includes definitions, just place the include folder inside a workspace. In that case, it will be used for definitions only.


something like
```
Gamemode
> includes
> gamemode.pwn
```

**Comment by Jedrzej94** [comment]
I'm using sampctl with:

```	
"builds": [
		{
			"name": "main",
			"version": "3.10.10",
			"args": [
				"-;+",
				"-(+",
				"-d3"
			],
			"includes": [
				"modules"
			],
			"compiler": {}
		}
	]
```

so that's why you see my .pwn files are inside 'modules' folder.

**Comment by vijayymmeena** [comment]
no problems, I am working on a update, where you can define folders in tasks.json that can be used to find definitions only.

that will resolve your problem?

**Comment by Jedrzej94** [comment]
> and if you want to load includes definitions, just place the include folder inside a workspace. In that case, it will be used for definitions only.
> 
> something like
> 
> ```
> Gamemode
> > includes
> > gamemode.pwn
> ```

What do you mean? You'd like me to move my `modules` into `gamemodes\includes` ? That's a bit of difficult task for me to be honest with you. If I would have to do that then I'm better off without the extension:)



> no problems, I am working on a update, where you can define folders in tasks.json that can be used to find definitions only.
> 
> that will resolve your problem?

I mean, if you would be able to support custom-folders for modular programming project types and make it work then yeah, for sure that would solve my problem:)

**Comment by vijayymmeena** [comment]
the update will have options to customize scan directories by just adding them in tasks.json

for example
```
DefScanDirectories: [
   "gamemodes",
   "pawn/includes"
]
```

if you want to share any other suggestions regarding this, then now might be the good time.

**Comment by Jedrzej94** [comment]
Nope, I'm not seeing any other suggestions to be fair. I was just after the Go to definition, since I have a big project going on here and finding it manually always is a killer for me.

Honestly, there are many modern features missing such as Ctrl K+D (auto code indentation) - I was looking for this one on many extentions unfortunately didn't found one.

About auto-complete feature, I find the one made by Southclaws a little bit more friendly but it might be because I am way too used to his, since I've used it all the time but his extension is missing core features so I wanted to try yours.

//
I was about to "rant" also at auto-complete feature but I made a spelling mistake and it didn't suggest me my function lol. I was calling "SetPlayerStatus" but was doing "SetPla**t**erStatus" and was like "ugh, another feature broken" - but no, it is working just fine.

![image](https://user-images.githubusercontent.com/15942408/110015880-aece9180-7d24-11eb-9dd9-9c5584fe919c.png)

**Comment by vijayymmeena** [comment]
well if you can join our discord channel, then we can discuss all the problems and I will be happy to improve my plugin. as you know, live decussation is hard here. however, I will update when the above mentioned update is ready.

**Comment by Jedrzej94** [comment]
Sure, I'll just wait for an info. I'd like to join your Discord server but that phone verification threw me off, sorry.

![image](https://user-images.githubusercontent.com/15942408/110016656-96ab4200-7d25-11eb-8592-6bb0bf171b93.png)

**Comment by vijayymmeena** [comment]
you can bypass that but for that you need to register at https://forum.iorp.in or verify phone. let me know which option you choose.

**Comment by vijayymmeena** [comment]
![image](https://user-images.githubusercontent.com/43092101/110041704-8d909400-7d6a-11eb-9275-2c61dbf4051f.png)
1. execute this command.
2. define relative paths of folders from where the definitions files exists. just like below screnshots.

![image](https://user-images.githubusercontent.com/43092101/110041816-c3357d00-7d6a-11eb-837e-7e4db01ffb57.png)
in this screenshot, only gamemodes folder files definitions are collected. and other folders like dependencies are not collected.

In my tests everything seems okay, if you have issues. Then reply this thread or contact at discord for further clarification.
This is optional update, normally extension scan all files in workspace but you can whitelist paths of workspace using above methods.

**Comment by Jedrzej94** [comment]
What's the first screenshot? Is it "Run Task" window? I can't seem to find it anywhere in VS Code.

edit://
nvm it's cmd palette

**Comment by Jedrzej94** [comment]
Okay, seems like it's working now. That's a shame it navigates to forwards only, I assume pawn limitations though and function would have to be public for it to work always.

Anyways, awesome mate. Thank you for quick fix on that!

**Comment by Jedrzej94** [comment]
Seems like extension doesn't work for me now at all. I've managed to break it somehow lol. Is there any cache somewhere of it that I should remove? Since uninstall & install doesn't seem to work.

Auto-complete feature doesn't even work anymore and Code Lens etc. literally it behaves like extension isn't there.

**Comment by vijayymmeena** [comment]
try deleting relative path file. you might have entered wrong paths.

**Comment by vijayymmeena** [comment]
send me discord friend request, my name is Harry_James in community server. And let me know other requests of yours for improvements.
