### ISSUE TITLE
QA: Wrong spaces

### ISSUE THREAD

**Issue by 14837-eng** [oceanroleplay/pawn-community-tool#5]
Spaces appear due to formatting and the compiler misunderstands the expression.
How to fix?
![image](https://user-images.githubusercontent.com/56313646/184890039-4ac4a33c-a0dc-47c0-832e-5d179f4d4553.png)

**Comment by 14837-eng** [comment]
spaces off topic (See operators with % and \ )
![image](https://user-images.githubusercontent.com/56313646/184894306-0d30813e-7ed1-4a17-a572-4e01ec866210.png)
![image](https://user-images.githubusercontent.com/56313646/184894273-db5c9aa4-a95b-461c-8df2-4bb28ad664a9.png)

**Comment by vijayymmeena** [comment]
provide plain code for testing

**Comment by 14837-eng** [comment]
Code  https://pastebin.com/C6zLK1M3

**Comment by vijayymmeena** [comment]
technically, there is no pawn code formatter, this extension use javascript formater, so there are limitations... I tried to fix it, but it does not work out. so, you can either not use formatter or use it within it's limits... if you can fix, will appreciate the PR.

I am closing this issue, as for mentioned reason. I can't help it, sorry.
