### ISSUE TITLE
QA: Incorrect formatting

### ISSUE THREAD

**Issue by 14837-eng** [oceanroleplay/pawn-community-tool#6]
How to remove line breaks in such situations when there is a constant substitution?

![image](https://user-images.githubusercontent.com/56313646/184891349-831fc529-ccf5-438a-b84a-2f870109bc85.png)

**Comment by vijayymmeena** [comment]
provide plain code for testing

**Comment by 14837-eng** [comment]
https://pastebin.com/bAPLZ07t

Code not for work. Code for example. 
for the code to work, you need to connect mysql R20

**Comment by vijayymmeena** [comment]
technically, there is no pawn code formatter, this extension use javascript formater, so there are limitations... I tried to fix it, but it does not work out. so, you can either not use formatter or use it within it's limits... if you can fix, will appreciate the PR.

I am closing this issue, as for mentioned reason. I can't help it, sorry.
